### ISSUE TITLE
checkpoints/KITTI_comb/checkpoint_best.ckpt always gives occlusion maps of all zeros

### ISSUE THREAD

**Issue by RK621** [avirambh/ScopeFlow#4]
Dear Authors,

1). I got occlusion maps of all zeros when evaluating using the pretrained model "checkpoints/KITTI_comb/checkpoint_best.ckpt".  

2). However, when I overwrite "checkpoints/KITTI_comb/checkpoint_best.ckpt" with the files moving from "checkpoints/Sintel_comb/checkpoint_best.ckpt", and did the same thing in 1), the occlusion map is not zero. 

Was the occlusion being trained when creating the checkpoint  "checkpoints/KITTI_comb/checkpoint_best.ckpt"?

Thank you very much!

=====
PS. 

My environment is 
python                    3.7.3
pytorch                   1.1.0
CUDA                      9.0

The correlation package has been installed based on the instruction in the IRR-PWC repository.

**Comment by avirambh** [comment]
Hi @RK621,

You are correct, we trained the occlusion estimator only for the Sintel models.
In order to retrain it with occlusion you'll need to change the [dataset loader of KITTI](https://github.com/avirambh/ScopeFlow/blob/master/datasets/kitti_combined.py).

Regards,
Aviram
